define("app/page/user-log-reg",["app/home","app/valid"],function(home,v){var doLogin=function(){var $this=$(".pageLoginBtn");if($(this).attr("disabled")=="disabled"){return;}
$this.html($("#common-loading-tmpl").render({data:"正在登录"}));$this.attr("disabled","disabled");if(v.doValidForm($("#pageLoginForm"))){$.ajax({url:"/login",type:"POST",data:home.generateFormData($("#pageLoginForm"))}).done(function(data){if(data.success==true){location.href=data.str;}else{home.error(data.message);}
$this.html("登录");$this.attr("disabled",false);});}else{$this.html("登录");$this.attr("disabled",false);}}
var doReg=function(){var $this=$(".pageRegisterBtn")
if($this.attr("disabled")=="disabled"){return;}
$this.html($("#common-loading-tmpl").render({data:"正在注册"}));$this.attr("disabled","disabled");if(v.doValidForm($("#pageRegForm"))){$.ajax({url:"/user/register",type:"POST",data:home.generateFormData($("#pageRegForm"))}).done(function(data){if(data.success==true){location.href="/p/people/people_info_perfect";}else{home.error(data.message);}
$this.html("注册");$this.attr("disabled",false);});}else{$this.html("注册");$this.attr("disabled",false);}}
return{init:function(){var md=window.location.hash;if(md!=""){md=md.replace("#","");if(md=="reg"){$("#pageRegForm").show();}else if(md=="forget"){$("#pageForgetPwdForm").show();}else{$("#pageLoginForm").show();}}else{$("#pageLoginForm").show();}
$(".pageToRegBtn").click(function(){$("#pageLoginForm").hide();$("#pageRegForm").show();$("#pageForgetPwdForm").hide();});$(".pageToLoginBtn").click(function(){$("#pageRegForm").hide();$("#pageLoginForm").show();$("#pageForgetPwdForm").hide();});$(".pageToForgetPwdBtn").click(function(){$("#pageRegForm").hide();$("#pageLoginForm").hide();$("#pageForgetPwdForm").show();});$("#pageLoginForm").find("input").keydown(function(event){if(event.which==13){doLogin();}});$("#pageRegForm").find("input").keydown(function(event){if(event.which==13){doReg();}});$(".pageLoginBtn").click(function(){doLogin();});$(".pageRegisterBtn").click(function(){doReg();});$(".pageForgetPwdBtn").click(function(){var $this=$(this);if($this.attr("disabled")=="disabled"){return;}
$this.html($("#common-loading-tmpl").render({data:"正在找回"}));$this.attr("disabled","disabled");if(v.doValidForm($("#pageForgetPwdForm"))){$.ajax({url:"/public/forget/pwd",type:"POST",data:home.generateFormData($("#pageForgetPwdForm"))}).done(function(data){if(data.success==true){home.success(data.message);}else{home.error(data.message);}
$this.html("找回密码");$this.attr("disabled",false);});}else{$this.html("找回密码");$this.attr("disabled",false);}});}};});