define(["app","app/home","app/valid","lib/magnific-popup"],function(app){app.controller("company_get_overview",['$rootScope','$scope','$http','companyService','peopleService','$timeout',function($rootScope,$scope,$http,companyService,peopleService,$timeout){var getCompanyProductImgs=function(){companyService.getCompanyProductImgs($scope.companyId).success(function(data){if(data.success==true){$scope.productImgs=data.responseData;$('.pro-popup').magnificPopup({delegate:'a',type:'image',tLoading:'Loading image #%curr%...',mainClass:'mfp-img-mobile',gallery:{enabled:true,navigateByImgClick:true,preload:[0,1]},image:{tError:'<a href="%url%"> #%curr%</a> 无法加载可能已删除.'}});}});};getCompanyProductImgs();var getCompanyWorkenvImgs=function(){companyService.getCompanyWorkEnvImgs($scope.companyId).success(function(data){if(data.success==true){$scope.workenvImgs=data.responseData;$('.env-popup').magnificPopup({delegate:'a',type:'image',tLoading:'Loading image #%curr%...',mainClass:'mfp-img-mobile',gallery:{enabled:true,navigateByImgClick:true,preload:[0,1]},image:{tError:'<a href="%url%"> #%curr%</a> 无法加载可能已删除.'}});}});}
getCompanyWorkenvImgs();var getCompanyFundingList=function(){companyService.getCompanyFundingList($scope.companyId).success(function(data){if(data.success==true){$scope.fundingList=data.responseData;}});}
getCompanyFundingList();var getCompanyMilestoneList=function(){companyService.getCompanyMilestoneList($scope.companyId).success(function(data){if(data.success==true){$scope.milestoneList=data.responseData;}});}
getCompanyMilestoneList();var getCompanyFounderList=function(){companyService.getCompanyFounderList($scope.companyId).success(function(data){if(data.success==true){$scope.founderList=data.responseData;$(".founder-list").dragsort("destroy");$(".founder-list").dragsort({dragSelector:"li",dragBetween:true,dragEnd:function(){var data=$(".founder-list li").map(function(){return $(this).data("id");}).get();$.ajax({url:"/company/founder/updateOrder/"
+ id,type:"POST",data:{ids:data.join(",")}})},placeHolderTemplate:"<li class=' founder-item placeHolder'><div></div></li>"});}});}
getCompanyFounderList();var getCompanyReportList=function(){companyService.getCompanyReportList($scope.companyId).success(function(data){if(data.success==true){$scope.reportList=data.responseData;}});}
getCompanyReportList();if($scope.isCreator=="true"){$scope.updateIntro=function(){companyService.updateCompany($scope.companyId,$scope.companyInfo).success(function(data){if(data.success==true){$scope.edit.intro=false;}});}
$scope.updateworkEnv=function(){companyService.updateCompany($scope.companyId,$scope.companyInfo).success(function(data){if(data.success==true){$scope.edit.workEnv=false;}});}
$scope.addFunding=function(){$http.post("/app/company/add/funding/"+ $scope.companyId,$.param($scope.funding)).success(function(data){if(data.success==true){getCompanyFundingList();$scope.funding={};$scope.edit.funding=false;}});};$scope.delFunding=function(fundingId){if(confirm("您确定要删除这条融资情况吗？")){companyService.delCompanyFundingById(fundingId).success(function(data){if(data.success=true){getCompanyFundingList();}});}};$scope.addReport=function(){$http.post("/app/company/add/report/"+ $scope.companyId,$.param($scope.report)).success(function(data){if(data.success){getCompanyReportList();$scope.edit.reports=false;$scope.report={};}});};$scope.delReportById=function(reportId){if(confirm("您确定要删除这篇报道文章吗？")){companyService.delCompanyReportById(reportId).success(function(data){if(data.success){getCompanyReportList();$scope.edit.reports=false;$scope.report={};}});}}
$scope.$watch("report.reportUrl",function(newVal,oldVal){if(newVal&&newVal.length>5){$http.post("/company/reports/url/title",$.param({url:newVal})).success(function(data){if(data.success){$scope.report.reportTitle=data.str;}});$scope.report.reportTitle=" ";}else if(oldVal){$scope.report.reportTitle='';}});$scope.addMilestone=function(){$http.post("/app/company/add/milestone/"+ $scope.companyId,$.param($scope.milestone)).success(function(data){if(data.success){getCompanyMilestoneList();$scope.edit.milestone=false;$scope.milestone={};}});};$scope.delMilestone=function(id){if(confirm("您确定要删除这条里程碑吗？")){companyService.delCompanyMilestoneById(id).success(function(data){if(data.success==true){getCompanyMilestoneList();}});}};$scope.$watch("productImgUrl",function(newVal,oldVal){if(newVal&&newVal.length>10){companyService.addCompanyProductImg($scope.companyId,newVal).success(function(data){if(data.success==true){getCompanyProductImgs();}});}});$scope.$watch("workenvImgUrl",function(newVal,oldVal){if(newVal&&newVal.length>10){companyService.addCompanyWorkenvImg($scope.companyId,newVal).success(function(data){console.log(data);if(data.success==true){getCompanyWorkenvImgs();}})}});$scope.delProductImg=function(imgId){if(confirm("您确定要删除这张产品图片吗？")){companyService.delCompanyImg(imgId).success(function(data){if(data.success==true){getCompanyProductImgs();}});}}
$scope.delWorkenvImg=function(imgId){if(confirm("您确定要删除这张工作环境图片吗？")){companyService.delCompanyImg(imgId).success(function(data){if(data.success==true){getCompanyWorkenvImgs();}});}}
$scope.getFounders=function(viewValue){return peopleService.findPeopleByNickname(viewValue);};$scope.addFounder=function(){companyService.addFounder(angular.extend({},$scope.founder,{"companyId":$scope.companyId})).success(function(data){if(data.success==true){$scope.edit.founder=false;$scope.founder='';$scope.selectFounder={};getCompanyFounderList();}});}
$scope.updateFounder=function(founder){companyService.updateFounder(founder).success(function(data){if(data.success){$scope.edit.founder=false;$scope.founder='';$scope.selectFounder={};getCompanyFounderList();}})};$scope.delFounder=function(founderId){if(confirm("您确定要删除这个团队成员吗？")){companyService.delFounder(founderId).success(function(){getCompanyFounderList();});}}}}]);return{init:function(){}};});