define(["app/home","app/valid","lib/bootstrap-tags","app"],function(home,valid,t,app){app.controller("company_add",['$scope','$http',function($scope,$http){$http.post("/app/incubator/list").success(function(data){$scope.ibs=data.responseData.rows;});$scope.initLocation=function(selIb,ibId){$("input[data-id='"+ ibId.incubatorId+"']").selectize({create:false,maxItems:null,valueField:'code',labelField:'value',searchField:'value',options:ibId.citysView,sortField:{field:'text',direction:'asc'},dropdownParent:'body'});return selIb;}
$scope.selIbCount=function(){if($("input[name='selIb']:checked").length>0)
return true;return false;}
$scope.checkApply=function(applyCheckBox){if(applyCheckBox==true){$("input[name='enterDate']").attr("data-init","false");home.converHtml();$("#bp").change(function(){var $span=$(this).prev();var $fileName=$(this).prev().prev();var $btn=$(this).parent();if($btn.attr("disabled")=="disabled"){return;}
$span.html($("#common-loading-tmpl").render({data:"正在上传"}));$btn.attr("disabled","disabled");var flist=$(this).val().split('\\');var length=flist.length;var fname=flist[length- 1];$.ajax({url:path
+"/attachment/getYunFileInfo",type:"POST",data:{fileName:fname}}).done(function(data){if(data.success==true){$.ajax({url:data.responseData.postUrl,type:'POST',data:home.buildFormData(data.responseData,$("#bp")),processData:false,contentType:false}).done(function(restr){restr=$.parseJSON(restr);if(restr.code==200){$("input[name='bp']").val(home.fileUrl
+ restr.url);$span.html("");$fileName.html(fname);$btn.attr("disabled",false);}else{$span.html("点击上传");$fileName.html("");$btn.attr("disabled",false);}});}else{home.error("请上传PDF、WORD、PPT、ZIP或RAR压缩文件");$span.html("选择文件");$fileName.html("");$btn.attr("disabled",false);}});});}
return applyCheckBox;}}]);var pId=0;return{init:function(){home.converHtml();$(".btn-next").click(function(){var $form=$(".wizard-content-1");if(valid.doValidForm($form)){if(!$("input[name='logo_img']").val()){home.error("请上传logo");return false;}
if(!$("select[name='industry']").val()){home.error("请选择所属行业")
return false;}
$(".wizard-content-1").hide();$(".wizard-content-2").show(300);$(".wizard-2").addClass("active");$(".wizard-1").removeClass("active");home.goTop();}});$(".btn-back").click(function(){$(".wizard-content-2").hide();$(".wizard-content-1").show(300);$(".wizard-2").removeClass("active");$(".wizard-1").addClass("active");home.goTop();});$(".btn-back2").click(function(){$(".wizard-content-3").hide();$(".wizard-content-2").show(300);$(".wizard-3").removeClass("active");$(".wizard-2").addClass("active");home.goTop();});$(".doCreateCompanyBtn").click(function(){var $form=$("#createCompanyForm");if(valid.doValidForm($form)){var $b=$(this);var c=$b.html();home.lbtn($b);$.ajax({url:"/company/create",type:"POST",data:home.generateFormData($form)}).done(function(data){if(data.success==true){var applyData=$("#applyIncubatorForm").find("input,textarea").serialize();$("input[name='selIb']:checked").each(function(){var ibId=$(this).val();var citys=$(this).parent().parent().parent().find("input[name='enterLocation']").val();$.ajax({url:"/app/incubator/apply/"
+ ibId+"?enterLocation="
+ citys,type:"POST",data:applyData});})
$(".wizard-content-2").hide();$(".wizard-content-3").show(300);$(".wizard-3").addClass("active");$(".wizard-2").removeClass("active");home.goTop();$(".btn-i-know").attr("href","/"+ data.str);}else{home.error(data.message);}
home.cbtn($b,c);});}
return false;});var v=window.setInterval(function(){var $s=$('select[name="industry"]');$s.selectize({maxItems:6});if($s.data("load")=="true"){window.clearInterval(v);}},100);home.uploadImg($("#logo"),"上传Logo",$("input[name='logo_img']"),$(".company_logo"),"_fixhw40","true");home.uploadImg($(".wechat2code"),"上传二维码",$("input[name='wechat2code']"),$(".wechat2code_img"),"_fixhw40");}};});