define(["app/home","lib/bootstrap-tags"],function(home){var loading=function(num){var isFollow=0;var isFilterType;if($(".company_follow").parent().hasClass("active")==true){var isFollow=1;}
if($(".company_zhhr").parent().hasClass("active")==true){var isFilterType=2;}
if($(".company_zyg").parent().hasClass("active")==true){var isFilterType=1;}
var $mask=$(".result_list");var _keyWordList=home.getDatasStr($("#bt-lists").find("span[data-key='keyword']"),"value");var _companySizeList=home.getDatasStr($("#bt-lists").find("span[data-key='companySize']"),"value");var _province=home.getDatasStr($("#bt-lists").find("span[data-key='province']"),"value");var _city=home.getDatasStr($("#bt-lists").find("span[data-key='city']"),"value");var _funding=home.getDatasStr($("#bt-lists").find("span[data-key='funding']"),"value");var _companySize=home.getDatasStr($("#bt-lists").find("span[data-key='companySize']"),"value");var _industry=home.getDatasStr($("#bt-lists").find("span[data-key='industry']"),"value");var _recruitStatus=home.getDatasStr($("#bt-lists").find("span[data-key='recruitStatus']"),"value");home.mask($mask);$.ajax({url:"/company/list",type:"POST",data:{page:num,rows:15,isFollow:isFollow,keyWordList:_keyWordList,companySizeList:_companySizeList,province:_province,city:_city,funding:_funding,industry:_industry,recruitStatus:_recruitStatus,isFilterType:isFilterType}}).done(function(data){if(data.success==true&&data.responseData.records>0){home.initList($("#result_list_ul"),$("#temp-company-list").render(data.responseData.rows),$("#next-div"),loading,data.responseData.currPage,data.responseData.total,"到世界尽头了呢～");home.converHtml();}else{$("#result_list_ul").html($("#temp-no-company-list").render({}));home.clearnext($("#next-div"),"到世界尽头了呢～");}
home.unmask($mask);});};return{init:function(){if($("#header_search").attr("data-init")!="true"){$(".dropdown-filter").hover(function(){$(this).find(".dropdown-box").show();},function(){$(this).find(".dropdown-box").hide();})
$(".industry-div").slimScroll({wheelStep:20});var $tag=$(".tagsinput").tagsinput();$(".tagsinput").on('itemAdded',function(event){loading(1);});$(".tagsinput").on('itemRemoved',function(event){loading(1);});var areaSel=$(".area-sel").selectize({valueField:'code',labelField:'value',searchField:'value',options:[],create:false,render:{option:function(item,escape){return'<div>'
+'<span class="title">'
+'<span class="name"><i class="icon '
+(item.value?'fork':'source')
+'"></i>'+ escape(item.value)
+'</span>'+'</div>';}},load:function(query,callback){if(!query.length)
return callback();$.ajax({url:'/area/search/'
+ encodeURIComponent(query),type:'post',error:function(){callback();},success:function(res){callback(res.slice(0,10));}});},onChange:function(code){if(code.length==6){$(".tagsinput").tagsinput("add",$(".area-sel").next().find(".item").html(),"province",code);}else if(code.length==10){$(".tagsinput").tagsinput("add",$(".area-sel").next().find(".item").html(),"city",code);}
loading(1);areaSel[0].selectize.clear();}});$("#header_search-filters").find("div[data-s-type]").find("div").click(function(){var $this=$(this);var isSole=$(this).parent().data("sole");var name=$this.text();var dataT=$this.parent().data("s-type");var dataValue=$this.data("s-v");var soleSpan=$("#bt-lists").find("span[data-key='"+ dataT
+"']");if(isSole==1&&soleSpan.length>0){soleSpan.html(name
+"<span data-role='remove'></span>");soleSpan.attr("data-value",dataValue);loading(1);}else{$("#s_"+ dataT).val(dataValue);$(".tagsinput").tagsinput("add",name,dataT,dataValue);}});$(".btn-search").click(function(){loading(1);});}
loading(1);$("#header_search").attr("data-init","true");}};});