define(["app/home","app/main","lib/bootstrap-tags","lib/jquery-ui","lib/magnific-popup"],function(home,main){var loading=function(num){var isFollow=0;if($(".job_follow").parent().hasClass("active")==true){var isFollow=1;}
var $mask=$(".job_list");var _keyWordList=home.getDatasStr($("#bt-lists").find("span[data-key='keyword']"),"value");var _jobPositionList=home.getDatasStr($("#bt-lists").find("span[data-key='jobPosition']"),"value");var _province=home.getDatasStr($("#bt-lists").find("span[data-key='province']"),"value");var _city=home.getDatasStr($("#bt-lists").find("span[data-key='city']"),"value");var _jobTypeList=home.getDatasStr($("#bt-lists").find("span[data-key='jobType']"),"value");var _salaryList=home.getDatasStr($("#bt-lists").find("span[data-key='salary']"),"value");var _stock=home.getDatasStr($("#bt-lists").find("span[data-key='stock']"),"value");var _funding=home.getDatasStr($("#bt-lists").find("span[data-key='funding']"),"value");var _companySize=home.getDatasStr($("#bt-lists").find("span[data-key='companySize']"),"value");home.mask($mask);$.ajax({url:"/jobs/list",type:"POST",data:{page:num,rows:15,isFollow:isFollow,keyWordList:_keyWordList,jobPositionList:_jobPositionList,province:_province,city:_city,jobTypeList:_jobTypeList,stock:_stock,funding:_funding,companySize:_companySize,salaryList:_salaryList}}).done(function(data){if(data.success==true&&data.responseData.records>0){home.initList($(".job_list"),$("#temp-jobs-list").render(data.responseData.rows),$("#next-job"),loading,data.responseData.currPage,data.responseData.total,"到世界尽头了呢～");initEvent();home.converHtml();}else{$(".job_list").html($("#temp-no-jobs-list").render({}));home.clearnext($("#next-job"),"到世界尽头了呢～");}
home.unmask($mask);});};var initEvent=function(){$(".job_row").unbind("click");$(".job_row").click(function(){var p=$(this);var idData=p.data("job_id");var t_bar=$(".t_bar-"+ idData);var details=$(".details-"+ idData);var $btn=t_bar.find(".btn-follow-job");if($(details).is(":hidden")){p.css("background-color","#f5f5f5");}else{p.css("background-color","");}
if($btn.attr("data-loading")=="no"){$.ajax({url:"/jobs/get/more/"+ idData,type:"POST",data:{jobId:idData}}).done(function(data){if(data.success==true){if(data.responseData.isFollow=="yes"){$btn.html("<i class='fa fa-star'></i> 取消收藏");}else{$btn.html("<i class='fa fa-star-o'></i> 加入收藏");}
details.html(home.tobn($("#temp-job-more").render(data.responseData)));home.imgpup(details.find('.pro-popup'));home.imgpup(details.find('.env-popup'));$btn.attr("data-loading","yes");t_bar.slideToggle(310);details.slideToggle(310);}});}else{t_bar.slideToggle(310);details.slideToggle(310);}});$(".btn-follow-job").unbind("click");$(".btn-follow-job").click(function(){var $btn=$(this);var _jobId=$btn.data("id");$.ajax({url:"/jobs/follow",type:"POST",data:{jobId:_jobId}}).done(function(data){if(data.success==true){home.alertFloatMessage($btn,data.message);if(data.str=="del"){$btn.html("<i class='fa fa-star-o'></i> 加入收藏");}
if(data.str=="add"){$btn.html("<i class='fa fa-star'></i> 取消收藏");}}else{home.alertFloatMessage($btn,data.message);}});});};return{init:function(){home.converHtml();$(".dropdown-filter").hover(function(){$(this).find(".dropdown-box").show();},function(){$(this).find(".dropdown-box").hide();})
$("#slider-range").slider({range:true,min:0,max:50,values:[0,50],slide:function(event,ui){$("#search_amount").html("￥"+ ui.values[0]
+"k - ￥"+ ui.values[1]+"k");},stop:function(event,ui){var salarySpan=$("#bt-lists").find("span[data-key='salary']");if(salarySpan.length>0){salarySpan.html("￥"+ ui.values[0]+"k - ￥"
+ ui.values[1]+"k"
+"<span data-role='remove'></span>");salarySpan.attr("data-value",ui.values[0]
+"-"+ ui.values[1]+"");}else{$(".tagsinput").tagsinput("add","￥"+ ui.values[0]+"k - ￥"
+ ui.values[1]+"k","salary",ui.values[0]+"-"+ ui.values[1]);}
loading(1);}});var areaSel=$(".area-sel").selectize({valueField:'code',labelField:'value',searchField:'value',options:[],create:false,render:{option:function(item,escape){return'<div>'+'<span class="title">'
+'<span class="name"><i class="icon '
+(item.value?'fork':'source')
+'"></i>'+ escape(item.value)
+'</span>'+'</div>';}},load:function(query,callback){if(!query.length)
return callback();$.ajax({url:'/area/search/'
+ encodeURIComponent(query),type:'post',error:function(){callback();},success:function(res){callback(res.slice(0,10));}});},onChange:function(code){if(code.length==6){$(".tagsinput").tagsinput("add",$(".area-sel").next().find(".item").html(),"province",code);}else if(code.length==10){$(".tagsinput").tagsinput("add",$(".area-sel").next().find(".item").html(),"city",code);}
loading(1);areaSel[0].selectize.clear();}});var $tag=$(".tagsinput").tagsinput();$(".tagsinput").on('itemAdded',function(event){loading(1);});$(".tagsinput").on('itemRemoved',function(event){loading(1);});$("#header_search-filters").find("div[data-s-type]").find("div").click(function(){var $this=$(this);var isSole=$(this).parent().data("sole");var name=$this.text();var dataT=$this.parent().data("s-type");var dataValue=$this.data("s-v");var soleSpan=$("#bt-lists").find("span[data-key='"+ dataT+"']");if(isSole==1&&soleSpan.length>0){soleSpan.html(name
+"<span data-role='remove'></span>");soleSpan.attr("data-value",dataValue);loading(1);}else{$("#s_"+ dataT).val(dataValue);$(".tagsinput").tagsinput("add",name,dataT,dataValue);}});$(".btn-search").click(function(){loading(1);});loading(1);}};});