define(["app","app/home","app/valid"],function(app,home,v){app.controller("incubator_get_comment",['$scope','$location',function($scope,$location){var id=$("#pId").val();var loading=function(){$.ajax({url:"/company/comment/list/"+ id,type:"POST"}).done(function(data){if(data.success==true&&data.responseData.records>0){$(".comment-list-ul").html($("#comment-list-item").render(data.responseData.rows));$(".btn-show-comment").click(function(){var $cid=$(this).data("c-id");$(".c-comment[data-c-id='"+ $cid+"']").slideToggle(310);loadingc($cid);});$(".btn-send-c").click(function(){var $cid=$(this).data("c-id");if(v.doValidForm($("#c-form-"+ $cid))){var $b=$(this);var c=$b.html();home.lbtn($b);$.ajax({url:"/company/comment/c/add/"+ $cid,type:"POST",data:home.generateFormData($("#c-form-"
+ $cid))}).done(function(data){if(data.success==true){$("#c-form-"+ $cid).find("textarea").val("");loadingc($cid);}});home.cbtn($b,c);}});$(".c-up").click(function(){var $cid=$(this).data("c-id");var $btn=$(this);$.ajax({url:"/company/comment/up/"+ $cid,type:"POST"}).done(function(data){if(data.success==true){if(data.success==true){home.alertFloatMessage($btn,data.message);if(data.str=="del"){$btn.html("<i class='fa fa-thumbs-o-up'>");$btn.prev().html(parseInt($btn.prev().html())
- 1);}
if(data.str=="add"){$btn.html("<i class='fa fa-thumbs-up'>");$btn.prev().html(parseInt($btn.prev().html())
+ 1);}}else{home.alertFloatMessage($btn,data.message);}}else{}});});}});var loadingc=function(cid){$.ajax({url:"/company/comment/c/list/"+ cid,type:"POST"}).done(function(data){if(data.success==true&&data.responseData.records>0){$("#clist-ul-"+ cid).html($("#comment-list-c-item").render(data.responseData.rows));$(".comment-c-up").click(function(){var $cid=$(this).data("c-id");var $btn=$(this);$.ajax({url:"/company/comment/up/"+ $cid,type:"POST"}).done(function(data){if(data.success==true){if(data.success==true){home.alertFloatMessage($btn,data.message);if(data.str=="del"){$btn.html("<i class='fa fa-thumbs-o-up'>");$btn.prev().html(parseInt($btn.prev().html())
- 1);}
if(data.str=="add"){$btn.html("<i class='fa fa-thumbs-up'>");$btn.prev().html(parseInt($btn.prev().html())
+ 1);}}else{home.alertFloatMessage($btn,data.message);}}else{}});});}});};};id=$("#pId").val();if(!id){return;}
loading();$(".btn-post-comment").click(function(){if(v.doValidForm($("#c_c_f"))){var $b=$(this);var c=$b.html();home.lbtn($b);$.ajax({url:"/company/comment/add/"+ id,type:"POST",data:home.generateFormData($("#c_c_f"))}).done(function(data){if(data.success==true){$("#c_c_f").find("textarea").val("");loading();}
home.cbtn($b,c);});}});}]);return{init:function(){}};});